backend:
  name: github
  repo: mrocha98/mrocha.xyz
  branch: main

locale: pt
site_url: https://mrocha.xyz
publish_mode: editorial_workflow
media_folder: static/assets/uploads
public_folder: /assets/uploads
slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: posts
    label: Posts
    label_singular: post
    folder: content/posts
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    identifier_field: postTitle
    sortable_fields: ['postDate', 'commit_date', 'postTitle', 'postCategory']
    summary: '[{{postCategory}}] {{postTitle}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'post',
          required: true,
        }
      - {
          label: 'Título',
          name: 'postTitle',
          widget: 'string',
          hint: 'entre 50 a 60 caracteres (recomendado). Referência: <https://moz.com/learn/seo/title-tag>',
          required: true,
        }
      - {
          label: 'Data de publicação',
          name: 'postDate',
          widget: 'datetime',
          format: 'YYYY-MM-DD hh:mm:ss',
          required: true,
        }
      - {
          label: 'Descrição',
          name: 'postDescription',
          widget: 'text',
          pattern: ['^.{50,160}$', 'Deve ter entre 50 a 160 caracteres'],
          hint: 'entre 50 a 160 caracteres. Referência: <https://moz.com/learn/seo/meta-description>',
          required: false,
        }
      - {
          label: 'Thumbnail',
          name: 'postThumbnail',
          widget: 'image',
          allow_multiple: false,
          required: false,
        }
      - {
          label: 'Texto alternativo',
          name: 'postAltText',
          widget: 'string',
          hint: 'Utilizado por leitores de tela e quando a thumbnail não carregar. Considere como obrigatório caso tenha definido uma thumbnail.',
          default: '',
          required: false,
        }
      - {
          label: 'Em destaque',
          name: 'postIsFeatured',
          widget: 'boolean',
          required: false,
        }
      - {
          label: 'Categoria',
          name: 'postCategory',
          widget: 'relation',
          multiple: false,
          collection: 'categories',
          search_fields: ['categoryName'],
          value_field: 'categoryName',
          required: true,
        }
      - {
          label: 'Tags',
          label_singular: 'tag',
          name: 'postTags',
          widget: 'relation',
          multiple: true,
          collection: 'tags',
          search_fields: ['tagName'],
          display_fields: ['tagName'],
          value_field: '{{tagName}}',
          default: [],
          required: false,
        }
      - {
          label: 'Referências',
          label_singular: 'referência',
          name: 'postReferences',
          widget: 'list',
          default: [],
          required: false,
          summary: '{{fields.title}} - {{fields.link}}',
          fields:
            [
              { label: 'Título', name: 'title', widget: 'string', default: '' },
              { label: 'Link', name: 'link', widget: 'string', default: '' },
            ],
        }
      - {
          label: 'Conteúdo',
          name: 'body',
          widget: 'markdown',
          required: true,
          buttons:
            [
              'bold',
              'italic',
              'code',
              'link',
              'heading-two',
              'heading-three',
              'heading-four',
              'heading-five',
              'heading-six',
              'quote',
              'bulleted-list',
              'numbered-list',
            ],
        }

  - name: categories
    label: Categorias
    label_singular: categoria
    folder: content/categories
    create: true
    identifier_field: 'categoryName'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'categoria',
          required: true,
        }
      - {
          label: 'Nome',
          name: 'categoryName',
          widget: 'string',
          required: true,
          hint: 'entre 3 a 16 caracteres. kebab-case.',
          pattern:
            [
              '^[a-z-]{3,}$',
              'Apenas letras minúsculas e traços. Deve ter entre 3 a 16 caracteres.',
            ],
        }

  - name: tags
    label: Tags
    label_singular: tag
    folder: content/tags
    create: true
    identifier_field: 'tagName'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'tag',
          required: true,
        }
      - {
          label: 'Nome',
          name: 'tagName',
          widget: 'string',
          required: true,
          hint: 'entre 3 a 27 caracteres. kebab-case.',
          pattern:
            [
              '^[a-z-]{3,27}$',
              'Apenas letras minúsculas e traços. Deve ter entre 3 a 27 caracteres.',
            ],
        }

  - name: projects
    label: Projetos
    label_singular: projeto
    folder: content/projects
    create: true
    identifier_field: projectTitle
    sortable_fields:
      ['projectCreationDate', 'commit_date', 'projectTitle', 'projectType']
    summary: '[{{projectType}}] {{projectTitle}}'
    fields:
      - {
          label: 'Título',
          name: 'projectTitle',
          widget: 'string',
          required: true,
        }
      - {
          label: 'Tipo',
          name: 'projectType',
          widget: 'select',
          required: true,
          options: ['acadêmico', 'freelance', 'open-source', 'trabalho formal'],
          default: 'freelance',
        }
      - {
          label: 'Data de criação',
          name: 'projectCreationDate',
          widget: 'datetime',
          format: 'YYYY-MM-DD hh:mm:ss',
          required: true,
        }
      - {
          label: 'Tecnologias',
          label_singular: 'tecnologia',
          name: 'projectTechs',
          widget: 'list',
          multiple: true,
          min: 1,
          summary: '{{fields.name}}',
          fields:
            [
              {
                label: 'Nome',
                name: 'name',
                widget: 'select',
                options:
                  [
                    'javascript',
                    'typescript',
                    'python',
                    'java',
                    'reactjs',
                    'angularjs',
                    'sass',
                    'postcss',
                    'tailwindcss',
                    'bootstrap',
                    'styled-components',
                    'material-ui',
                    'gatsbyjs',
                    'nextjs',
                    'nodejs',
                    'mongodb',
                    'storybook',
                    'graphql',
                    'jest',
                    'testing-library',
                    'godot engine',
                  ],
                required: true,
              },
              {
                label: 'Ícone',
                name: 'icon',
                widget: 'image',
                allow_multiple: false,
                required: true,
              },
            ],
        }
      - {
          label: 'Links',
          name: 'projectLinks',
          widget: 'object',
          required: false,
          summary: '{{fields.app}} | {{fields.sourceCode}}',
          fields:
            [
              {
                label: 'Aplicação',
                name: 'app',
                widget: 'string',
                required: false,
              },
              {
                label: 'Código Fonte',
                name: 'sourceCode',
                widget: 'string',
                required: false,
              },
            ],
        }
      - {
          label: 'Licença',
          name: 'projectLicense',
          widget: 'object',
          required: false,
          summary: '{{fields.name}} - {{fields.spdx}}',
          hint: 'Preencher os campos com os valores presentes no link: <https://spdx.org/licenses/>',
          fields:
            [
              {
                label: 'Nome',
                name: 'name',
                widget: 'string',
                hint: 'Nome completo da licença',
                required: false,
              },
              {
                label: 'SPDX',
                name: 'spdx',
                widget: 'string',
                hint: 'Sigla identificadora',
                required: false,
              },
            ],
        }
      - {
          label: 'Imagens',
          name: 'projectImages',
          widget: 'list',
          required: false,
          multiple: true,
          summary: '{{fields.alt}}',
          fields:
            [
              {
                label: 'src',
                name: 'src',
                widget: 'image',
                allow_multiple: false,
                required: false,
              },
              { label: 'alt', name: 'alt', widget: 'string', required: false },
              {
                label: 'Em destaque',
                name: 'isFeatured',
                widget: boolean,
                required: false,
              },
            ],
        }
      - {
          label: 'Conteúdo',
          name: 'body',
          widget: 'markdown',
          required: true,
          buttons: ['bold', 'italic', 'link', 'bulleted-list', 'numbered-list'],
          editor_components: [],
        }
